### ISSUE TITLE
Password exposed

### ISSUE THREAD

**Issue by ghost** [flaviano-defusco/workSampleO-war#1]
Hi, your Github credentials are exposed here https://github.com/flaviano-defusco/workSampleO-war/blob/211237c63e907fa6fdfe1551b0d232f2e3849582/gradle.properties

**Comment by flaviano-defusco** [comment]
Thanks again for your stand-up.
Will erase the file.

Flaviano.

**Comment by ghost** [comment]
Have a nice day
